myConsciousness/atproto.dart

.vscode/settings.json, packages/bluesky_post/.dockerignore, packages/bluesky_post/.gitignore, packages/bluesky_post/CHANGELOG.md, packages/bluesky_post/Dockerfile, packages/bluesky_post/README.md, packages/bluesky_post/action.yaml, packages/bluesky_post/bin/server.dart, packages/bluesky_post/lib/post.dart, packages/bluesky_post/pubspec.yaml, packages/bluesky_post/test/server_test.dart
=> feat: add `bluesky_post`

packages/bluesky_post/bin/server.dart
=> fix: fixed import

packages/atproto/CONTRIBUTION, packages/atproto/pubspec.yaml, packages/atproto_core/CONTRIBUTION, packages/atproto_core/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/CONTRIBUTION, packages/bluesky/README.md, packages/bluesky/lib/src/service/feeds/feeds_service.dart, packages/bluesky/lib/src/service/notifications/notifications_service.dart, packages/bluesky/pubspec.yaml
=> fix: fixed bugs

packages/bluesky_post/pubspec.yaml
=> fix: fixed version of `bluesky`

.vscode/settings.json, README.md
=> docs: add root readme

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/service/actors/actors_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/service/actors/actors_service_test.dart, packages/bluesky/test/src/service/actors/data/lookup_profile.json, packages/bluesky/test/src/service/actors/data/lookup_profiles.json, packages/bluesky/test/src/service/actors/data/search_actors.json, packages/bluesky/test/src/service/feeds/data/create_post.json
=> fix: fixed for the issue (#68)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/service/entities/feeds.dart
=> fix: fixed for the issue (#51)

packages/atproto/lib/src/atproto.dart, packages/atproto_core/lib/src/client/client_context.dart, packages/bluesky/lib/src/bluesky.dart, packages/bluesky/test/src/service/feeds/feeds_service_test.dart
=> fix: fixed for the issue (#71)

.vscode/settings.json, packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/service/entities/post_record.dart, packages/bluesky/lib/src/service/entities/post_record.freezed.dart, packages/bluesky/lib/src/service/entities/post_record.g.dart, packages/bluesky/lib/src/service/entities/post_ref.dart, packages/bluesky/lib/src/service/entities/post_ref.freezed.dart, packages/bluesky/lib/src/service/entities/post_ref.g.dart, packages/bluesky/lib/src/service/entities/strong_ref.dart, packages/bluesky/lib/src/service/entities/strong_ref.freezed.dart, packages/bluesky/lib/src/service/entities/strong_ref.g.dart, packages/bluesky/lib/src/service/feeds/feeds_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/service/feeds/data/create_repost.json, packages/bluesky/test/src/service/feeds/feeds_service_test.dart
=> feat: fixed for the issue (#36)

STYLEGUIDE.md, packages/atproto/CHANGELOG.md, packages/atproto/README.md, packages/atproto/example/example.dart, packages/atproto/lib/src/service/repositories/repositories_service.dart, packages/atproto/pubspec.yaml, packages/atproto/test/src/service/repositories/repositories_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/example/example.dart, packages/bluesky/lib/src/service/feeds/feeds_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/service/feeds/feeds_service_test.dart
=> fix: fixed for the issue (#81)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/service/feeds/feeds_service.dart, packages/bluesky/test/src/service/feeds/data/create_like.json, packages/bluesky/test/src/service/feeds/feeds_service_test.dart
=> feat: fixed for the issue (#33)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/service/feeds/feeds_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/service/feeds/data/get_feeds.json, packages/bluesky/test/src/service/feeds/feeds_service_test.dart
=> feat: fixed for the issue (#47)

packages/atproto/README.md, packages/bluesky/README.md
=> docs: fixed docs

packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/service/entities/like.dart, packages/bluesky/lib/src/service/entities/like.freezed.dart, packages/bluesky/lib/src/service/entities/like.g.dart, packages/bluesky/lib/src/service/entities/likes.dart, packages/bluesky/lib/src/service/entities/likes.freezed.dart, packages/bluesky/lib/src/service/entities/likes.g.dart, packages/bluesky/lib/src/service/feeds/feeds_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/service/feeds/data/find_likes.json, packages/bluesky/test/src/service/feeds/feeds_service_test.dart
=> feat: fixed for the issue (#37)

packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/service/entities/follows.dart, packages/bluesky/lib/src/service/entities/follows.freezed.dart, packages/bluesky/lib/src/service/entities/follows.g.dart, packages/bluesky/lib/src/service/feeds/feeds_service.dart, packages/bluesky/lib/src/service/graphs/graphs_service.dart, packages/bluesky/test/src/service/graphs/data/find_follows.json, packages/bluesky/test/src/service/graphs/graphs_service_test.dart
=> feat: fixed for the issue (#26)

packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/service/entities/followers.dart, packages/bluesky/lib/src/service/entities/followers.freezed.dart, packages/bluesky/lib/src/service/entities/followers.g.dart, packages/bluesky/lib/src/service/graphs/graphs_service.dart, packages/bluesky/test/src/service/graphs/data/find_followers.json, packages/bluesky/test/src/service/graphs/graphs_service_test.dart
=> feat: fixed for the issue (#28)

packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/service/actors/actors_service.dart, packages/bluesky/lib/src/service/entities/users.dart, packages/bluesky/lib/src/service/entities/users.freezed.dart, packages/bluesky/lib/src/service/entities/users.g.dart, packages/bluesky/test/src/service/actors/actors_service_test.dart, packages/bluesky/test/src/service/actors/data/find_suggestions.json
=> feat: fixed for the issue (#44)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/service/entities/post.dart, packages/bluesky/lib/src/service/entities/post.freezed.dart, packages/bluesky/lib/src/service/entities/post.g.dart, packages/bluesky/pubspec.yaml
=> fix: fixed for the issue (#96)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/service/entities/embed.dart, packages/bluesky/lib/src/service/entities/embed.freezed.dart, packages/bluesky/lib/src/service/entities/embed.g.dart, packages/bluesky/lib/src/service/entities/post_record.dart, packages/bluesky/lib/src/service/entities/post_record.freezed.dart, packages/bluesky/lib/src/service/entities/post_record.g.dart, packages/bluesky/lib/src/service/entities/reason.dart, packages/bluesky/lib/src/service/entities/reason.freezed.dart, packages/bluesky/lib/src/service/entities/reason.g.dart
=> feat: added `$type` fields (#97)

.vscode/settings.json, packages/bluesky_cards/README.md, packages/bluesky_cards/example/lib/main.dart, packages/bluesky_cards/example/pubspec.yaml, packages/bluesky_cards/example/pubspec_overrides.yaml, packages/bluesky_cards/lib/src/embedded_card.dart, packages/bluesky_cards/pubspec.yaml
=> feat: fixed for the issue (#105)

packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/service/entities/mutes.dart, packages/bluesky/lib/src/service/entities/mutes.freezed.dart, packages/bluesky/lib/src/service/entities/mutes.g.dart, packages/bluesky/lib/src/service/graphs/graphs_service.dart, packages/bluesky/test/src/service/graphs/data/find_mutes.json, packages/bluesky/test/src/service/graphs/graphs_service_test.dart
=> feat: fixed for the issue (#25)

.github/labeler.yml, .vscode/settings.json, packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/bluesky.dart, packages/bluesky/lib/src/service/bluesky_service.dart, packages/bluesky/lib/src/service/unspecced/unspecced_service.dart, packages/bluesky/test/src/service/unspecced/data/find_popular_feeds.json, packages/bluesky/test/src/service/unspecced/unspecced_service_test.dart
=> feat: fixed for the issue (#117)

.vscode/settings.json, packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/service/actors/actors_service.dart, packages/bluesky/lib/src/service/entities/actor_typeahead.dart, packages/bluesky/lib/src/service/entities/actor_typeahead.freezed.dart, packages/bluesky/lib/src/service/entities/actor_typeahead.g.dart, packages/bluesky/test/src/service/actors/actors_service_test.dart, packages/bluesky/test/src/service/actors/data/search_actor_typeahead.json
=> feat: fixed for the issue (#49)

packages/bluesky_post/CHANGELOG.md, packages/bluesky_post/README.md, packages/bluesky_post/action.yaml, packages/bluesky_post/lib/post.dart, packages/bluesky_post/pubspec.yaml
=> feat: fixed for the issue (#66)

packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/atproto_core.dart, packages/atproto_core/lib/src/client/challenge.dart, packages/atproto_core/lib/src/client/client_context.dart, packages/atproto_core/lib/src/serializable.dart, packages/atproto_core/lib/src/service_helper.dart, packages/atproto_core/pubspec.yaml, packages/bluesky/pubspec.yaml
=> refactor: fixed for the issue (#128)

README.md, packages/at_identifier/README.md, packages/at_uri/README.md, packages/atproto/README.md, packages/bluesky/README.md, packages/bluesky_cards/README.md, packages/nsid/README.md
=> fix: fixed brand links

.vscode/settings.json, packages/at_identifier/CHANGELOG.md, packages/at_identifier/pubspec.yaml, packages/at_uri/CHANGELOG.md, packages/at_uri/README.md, packages/at_uri/example/example.dart, packages/at_uri/lib/at_uri.dart, packages/at_uri/lib/src/invalid_at_uri_error.dart, packages/at_uri/lib/src/validation.dart, packages/at_uri/pubspec.yaml, packages/at_uri/pubspec_overrides.yaml, packages/at_uri/test/src/validation_test.dart, packages/nsid/CHANGELOG.md, packages/nsid/lib/nsid.dart, packages/nsid/lib/src/nsid.dart, packages/nsid/lib/src/validation.dart
=> feat: fixed for the issue (#140)

packages/at_uri/CHANGELOG.md, packages/at_uri/pubspec.yaml
=> fix: fixed initial version

packages/at_uri/CHANGELOG.md, packages/at_uri/lib/src/at_uri.dart, packages/at_uri/pubspec.yaml, packages/at_uri/test/src/at_uri_test.dart
=> fix: fixed for the issue (#149)

.gitignore, bin/mirror_lexicons.dart, melos.yaml, pubspec.yaml
=> feat: added script to mirror lexicons (#116)

lexicons/DISCLAIMER.md
=> docs: added Disclaimer

packages/bluesky/lib/src/bluesky.dart, packages/bluesky/lib/src/bluesky_service.dart
=> feat: fixed for the issue (#168)

packages/atproto/pubspec.yaml, packages/atproto_core/lib/src/base_service.dart, packages/atproto_core/pubspec.yaml, packages/bluesky_cli/pubspec.yaml, packages/xrpc/CHANGELOG.md, packages/xrpc/lib/src/xrpc.dart, packages/xrpc/pubspec.yaml, packages/xrpc/test/src/xrpc_test.dart
=> feat: fixed for the issue (#174)

packages/atproto/pubspec.yaml, packages/atproto_core/pubspec.yaml, packages/bluesky_cli/pubspec.yaml, packages/xrpc/CHANGELOG.md, packages/xrpc/lib/src/exception/xrpc_exception.dart, packages/xrpc/pubspec.yaml
=> fix: fixed for the issue (#177)

packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/bin/bsky.dart, packages/bluesky_cli/lib/src/version.g.dart, packages/bluesky_cli/pubspec.yaml
=> fix: fixed

.vscode/settings.json, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/bsky_command.dart, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command/common/delete.dart, packages/bluesky_cli/lib/src/command/create_record_command.dart, packages/bluesky_cli/lib/src/command/delete_record_command.dart, packages/bluesky_cli/lib/src/command/feed/feed.dart, packages/bluesky_cli/lib/src/command/feed/like.dart, packages/bluesky_cli/lib/src/command/feed/likes.dart, packages/bluesky_cli/lib/src/command/feed/post.dart, packages/bluesky_cli/lib/src/command/feed/repost.dart, packages/bluesky_cli/lib/src/command/feed/reposted_by.dart, packages/bluesky_cli/lib/src/command/feed/thread.dart, packages/bluesky_cli/lib/src/command/feed/timeline.dart, packages/bluesky_cli/lib/src/command/procedure_command.dart, packages/bluesky_cli/lib/src/command_runner.dart, packages/bluesky_cli/lib/src/version.g.dart, packages/bluesky_cli/pubspec.yaml
=> feat: supported `app.bsky.feed`

packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command/unspecced/popular.dart, packages/bluesky_cli/lib/src/command_runner.dart
=> feat: supported `app.bsky.unspecced`

packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command/notification/notification_count.dart, packages/bluesky_cli/lib/src/command/notification/notifications.dart, packages/bluesky_cli/lib/src/command/notification/seen_notifications.dart, packages/bluesky_cli/lib/src/command_runner.dart
=> feat: added `app.bsky.notification` (#184)

packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/bluesky_cli.dart, packages/bluesky_cli/lib/src/command/actor/actor_suggestions.dart, packages/bluesky_cli/lib/src/command/actor/actor_typeahead.dart, packages/bluesky_cli/lib/src/command/actor/profile.dart, packages/bluesky_cli/lib/src/command/actor/profiles.dart, packages/bluesky_cli/lib/src/command/actor/search_actors.dart, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command_runner.dart
=> feat: added `app.bsky.actor` (#182)

packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command/graph/follow.dart, packages/bluesky_cli/lib/src/command/graph/followers.dart, packages/bluesky_cli/lib/src/command/graph/follows.dart, packages/bluesky_cli/lib/src/command/graph/mute.dart, packages/bluesky_cli/lib/src/command/graph/mutes.dart, packages/bluesky_cli/lib/src/command/graph/unmute.dart, packages/bluesky_cli/lib/src/command_runner.dart, packages/bluesky_cli/lib/src/logger.dart, packages/bluesky_cli/lib/src/runner/bsky_runner.dart
=> feat: added `app.bsky.graph` (#183)

packages/bluesky/lib/src/graphs/graphs_service.dart, packages/bluesky/test/src/graphs/graphs_service_test.dart
=> fix: removed `declarationCid` (#189)

README.md
=> docs: added description about melos (#166)

README.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/procedure_command.dart, packages/bluesky_cli/lib/src/command/query_command.dart, packages/bluesky_cli/lib/src/command_runner.dart, packages/bluesky_cli/lib/src/runner/bsky_runner.dart, packages/bluesky_cli/lib/src/version.g.dart, packages/bluesky_cli/pubspec.yaml
=> feat: supported `--pretty` option (#193)

README.md, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/procedure_command.dart, packages/bluesky_cli/lib/src/command/query_command.dart, packages/bluesky_cli/lib/src/command_runner.dart, packages/bluesky_cli/lib/src/runner/bsky_runner.dart
=> feat: added `--status` and `--request` (#195)

packages/atproto_core/lib/atproto_core.dart, packages/atproto_core/lib/src/base_service.dart, packages/atproto_core/lib/src/client/anonymous_client.dart, packages/atproto_core/lib/src/client/auth_required_client.dart, packages/atproto_core/lib/src/client/client_context.dart, packages/atproto_core/lib/src/client/client_resolver.dart, packages/atproto_core/lib/src/client/user_context.dart, packages/atproto_core/test/src/client/client_resolver_test.dart, packages/atproto_core/test/src/client/user_context_test.dart
=> feat: added anonymous client (#173)

packages/atproto/lib/src/sessions/sessions_service.dart, packages/atproto/pubspec.yaml, packages/bluesky_post/CHANGELOG.md, packages/bluesky_post/README.md, packages/bluesky_post/action.yaml, packages/bluesky_post/lib/post.dart, packages/bluesky_post/pubspec_overrides.yaml
=> feat: fixed for the issue (#126)

website/docusaurus.config.js
=> fix: fixed config

.github/labeler.yml, packages/atproto/CHANGELOG.md, packages/atproto/README.md, packages/atproto/lib/atproto.dart, packages/atproto/lib/src/atproto.dart, packages/atproto/lib/src/atproto_service.dart, packages/atproto/lib/src/entities/report.dart, packages/atproto/lib/src/entities/report.freezed.dart, packages/atproto/lib/src/entities/report.g.dart, packages/atproto/lib/src/moderation/moderation_reason_type.dart, packages/atproto/lib/src/moderation/moderation_service.dart, packages/atproto/lib/src/moderation/report_subject.dart, packages/atproto/test/src/moderation/data/create_report_with_repo_ref.json, packages/atproto/test/src/moderation/data/create_report_with_strong_ref.json, packages/atproto/test/src/moderation/moderation_reason_type_test.dart, packages/atproto/test/src/moderation/moderation_service_test.dart
=> feat: supported `com.atproto.moderation.createReport` (#216)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/actors/actors_service.dart, packages/bluesky/lib/src/entities/actor_profile.dart, packages/bluesky/lib/src/entities/actor_profile.freezed.dart, packages/bluesky/lib/src/entities/actor_profile.g.dart, packages/bluesky/lib/src/entities/actor_typeahead_data.dart
=> fix: fixed for the issue (#201)

packages/bluesky_cards/example/pubspec_overrides.yaml, packages/bluesky_cards/lib/src/embedded_card.dart, packages/bluesky_cards/pubspec.yaml, packages/bluesky_cards/pubspec_overrides.yaml
=> fix: fixed package structure

packages/atproto/lib/src/servers/servers_service.dart, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/servers/servers_service.dart, packages/bluesky/test/src/servers/data/create_session.json, packages/bluesky/test/src/servers/servers_service_test.dart
=> refactor: fixed `createSession` for `bluesky`

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/identities/identities_service.dart, packages/atproto/pubspec.yaml, packages/bluesky/pubspec.yaml
=> refactor: fixed method id

packages/bluesky_post/CHANGELOG.md, packages/bluesky_post/README.md, packages/bluesky_post/action.yaml, packages/bluesky_post/lib/post.dart, packages/bluesky_post/pubspec.yaml
=> fix: fixed to use `bluesky v0.3.3`

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/entities/current_session.dart, packages/atproto/lib/src/entities/current_session.freezed.dart, packages/atproto/lib/src/entities/current_session.g.dart, packages/atproto/lib/src/entities/session.dart, packages/atproto/lib/src/entities/session.freezed.dart, packages/atproto/lib/src/entities/session.g.dart, packages/atproto/pubspec.yaml, packages/atproto/test/src/servers/data/create_session.json, packages/atproto/test/src/servers/data/find_current_session.json
=> feat: added `email` field (#235)

packages/atproto/CHANGELOG.md, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/xrpc/CHANGELOG.md, packages/xrpc/pubspec.yaml
=> refactor: downgraded `meta` (#242)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/actor_profile.dart, packages/bluesky/lib/src/entities/actor_profile.freezed.dart, packages/bluesky/lib/src/entities/actor_profile.g.dart, packages/bluesky/pubspec.yaml
=> fix: fixed for the issue (#244)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/reply_ref.dart, packages/bluesky/lib/src/entities/reply_ref.freezed.dart, packages/bluesky/lib/src/entities/reply_ref.g.dart, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/pubspec.yaml
=> feat: added `reply` parameter (#246)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/facet_link.dart, packages/bluesky/lib/src/entities/facet_link.freezed.dart, packages/bluesky/lib/src/entities/facet_link.g.dart, packages/bluesky/pubspec.yaml
=> fix: fixed record type (#252)

packages/atproto/CHANGELOG.md, packages/atproto/README.md, packages/atproto/lib/atproto.dart, packages/atproto/lib/src/entities/account.dart, packages/atproto/lib/src/entities/account.freezed.dart, packages/atproto/lib/src/entities/account.g.dart, packages/atproto/lib/src/servers/servers_service.dart, packages/atproto/pubspec.yaml, packages/atproto/test/src/servers/data/create_account.json, packages/atproto/test/src/servers/servers_service_test.dart
=> feat: supported `createAccount` (#256)

packages/atproto/CHANGELOG.md, packages/atproto/README.md, packages/atproto/lib/src/entities/invite_code.dart, packages/atproto/lib/src/entities/invite_code.freezed.dart, packages/atproto/lib/src/entities/invite_code.g.dart, packages/atproto/lib/src/servers/servers_service.dart, packages/atproto/test/src/servers/data/create_invite_code.json, packages/atproto/test/src/servers/servers_service_test.dart
=> feat: supported `createInviteCode`

packages/atproto/CHANGELOG.md, packages/atproto/README.md, packages/atproto/lib/atproto.dart, packages/atproto/lib/src/entities/app_password.dart, packages/atproto/lib/src/entities/app_password.freezed.dart, packages/atproto/lib/src/entities/app_password.g.dart, packages/atproto/lib/src/servers/servers_service.dart, packages/atproto/test/src/servers/data/create_app_password.json, packages/atproto/test/src/servers/servers_service_test.dart
=> feat: added `createAppPassword` (#277)

packages/atproto/CHANGELOG.md, packages/atproto/README.md, packages/atproto/lib/src/repositories/repositories_service.dart, packages/atproto/test/src/repositories/data/update_record.json, packages/atproto/test/src/repositories/repositories_service_test.dart
=> feat: supported `updateRecord` (#295)

packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/src/actors/actors_service.dart, packages/bluesky/test/src/actors/actors_service_test.dart, packages/bluesky/test/src/actors/data/update_profile.json
=> feat: supported `updateProfile`

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/unspecced/unspecced_service.dart, packages/bluesky/pubspec.yaml
=> feat: added `includeNsfw` (#329)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/post_thread_view_record.dart, packages/bluesky/lib/src/entities/post_thread_view_record.freezed.dart, packages/bluesky/lib/src/entities/post_thread_view_record.g.dart
=> fix: fixed for the issue (#335)

packages/atproto_core/CHANGELOG.md, packages/xrpc/CHANGELOG.md
=> docs: added changelog (#318)

packages/bluesky_text/README.md
=> docs: fixed example

packages/bluesky_text/test/src/bluesky_text_test.dart
=> fix: delete `print`

.vscode/settings.json, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/lib/src/command/create_record_command.dart, packages/bluesky_cli/lib/src/command/feed/post.dart, packages/bluesky_cli/lib/src/version.g.dart, packages/bluesky_cli/pubspec.yaml, packages/bluesky_cli/pubspec_overrides.yaml
=> fix: fixed for the issue (#291)

packages/atproto/CHANGELOG.md, packages/atproto/lib/atproto.dart, packages/atproto/lib/src/entities/label.dart, packages/atproto/lib/src/entities/label.freezed.dart, packages/atproto/lib/src/entities/label.g.dart, packages/atproto/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/actor.dart, packages/bluesky/lib/src/entities/actor.freezed.dart, packages/bluesky/lib/src/entities/actor.g.dart, packages/bluesky/lib/src/entities/actor_profile.dart, packages/bluesky/lib/src/entities/actor_profile.freezed.dart, packages/bluesky/lib/src/entities/actor_profile.g.dart, packages/bluesky/lib/src/entities/notification.dart, packages/bluesky/lib/src/entities/notification.freezed.dart, packages/bluesky/lib/src/entities/notification.g.dart, packages/bluesky/lib/src/entities/post.dart, packages/bluesky/lib/src/entities/post.freezed.dart, packages/bluesky/lib/src/entities/post.g.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/actors/data/search_actor_typeahead.json, packages/bluesky/test/src/feeds/data/find_likes.json, packages/bluesky/test/src/feeds/data/find_posts.json, packages/bluesky/test/src/feeds/data/find_reposted_by.json, packages/bluesky/test/src/notifications/data/find_notifications.json
=> feat: added `labels` fields (#346)

packages/bluesky/pubspec.yaml
=> fix: fixed version

packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/entities/entities.dart, packages/bluesky_text/lib/src/entities/entity.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/entities/entities_test.dart, packages/bluesky_text/test/src/entities/entity_test.dart
=> fix: fixed for the issue (#354)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/repositories/repositories_service.dart, packages/atproto/pubspec.yaml, packages/atproto/test/src/repositories/repositories_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/notification.dart, packages/bluesky/lib/src/entities/notification.freezed.dart, packages/bluesky/lib/src/entities/notification.g.dart, packages/bluesky/pubspec.yaml
=> fix: fixed notification object

packages/atproto/lib/src/entities/create_action.dart, packages/atproto/lib/src/entities/delete_action.dart, packages/atproto/lib/src/entities/parsed_did_doc.dart, packages/atproto/lib/src/entities/update_action.dart, packages/bluesky/lib/src/entities/embed_record_with_media.dart
=> fix: dart format --set-exit-if-changed .

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/post_thread_view_record.dart, packages/bluesky/lib/src/entities/post_thread_view_record.freezed.dart, packages/bluesky/lib/src/entities/post_thread_view_record.g.dart, packages/bluesky/test/src/feeds/data/find_post_thread.json
=> feat: added `parent` field (#364)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/entities/record.dart, packages/atproto/lib/src/entities/record.freezed.dart, packages/atproto/lib/src/entities/record_value.dart, packages/atproto/lib/src/entities/record_value.freezed.dart, packages/atproto/test/src/repositories/data/find_record_without_cid.json, packages/atproto/test/src/repositories/repositories_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/post.dart, packages/bluesky/lib/src/entities/post.freezed.dart, packages/bluesky/lib/src/entities/post.g.dart, packages/bluesky/lib/src/entities/post_thread_view_blocked.dart, packages/bluesky/lib/src/entities/post_thread_view_not_found.dart, packages/bluesky/test/src/feeds/feeds_service_test.dart
=> feat: added `toStrongRef()` (#367)

packages/atproto/CHANGELOG.md, packages/atproto/README.md, packages/atproto/lib/src/repositories/repositories_service.dart, packages/atproto/test/src/repositories/repositories_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/README.md
=> feat: added utilities for `updateBulk` (#371)

.vscode/settings.json, packages/atproto/lib/src/entities/create_action.dart, packages/atproto/lib/src/entities/create_action.freezed.dart, packages/atproto/lib/src/entities/create_action.g.dart, packages/atproto/lib/src/entities/update_action.dart, packages/atproto/lib/src/entities/update_action.freezed.dart, packages/atproto/lib/src/entities/update_action.g.dart, packages/atproto/lib/src/repositories/repositories_service.dart, packages/atproto/test/src/repositories/repositories_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/lib/src/graphs/graphs_service.dart, packages/bluesky/lib/src/params/post_param.dart, packages/bluesky/lib/src/params/post_param.freezed.dart, packages/bluesky/lib/src/params/post_param.g.dart, packages/bluesky/lib/src/params/repo_param.dart, packages/bluesky/lib/src/params/repo_param.freezed.dart, packages/bluesky/lib/src/params/repo_param.g.dart, packages/bluesky/lib/src/params/strong_ref_param.dart, packages/bluesky/lib/src/params/strong_ref_param.freezed.dart, packages/bluesky/lib/src/params/strong_ref_param.g.dart, packages/bluesky/test/src/feeds/feeds_service_test.dart, packages/bluesky/test/src/graphs/graphs_service_test.dart
=> feat: fixed for the issue (#373)

.all-contributorsrc, README.md
=> docs: added `all contributors` (#369)

packages/bluesky_post/CHANGELOG.md, packages/bluesky_post/README.md, packages/bluesky_post/action.yaml, packages/bluesky_post/lib/post.dart, packages/bluesky_post/pubspec.yaml, packages/bluesky_post/pubspec_overrides.yaml
=> feat: fixed for the issue (#384)

packages/bluesky_post/README.md
=> docs: added action

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/converter/reason_converter.dart, packages/bluesky/lib/src/entities/feed_view.dart, packages/bluesky/lib/src/entities/feed_view.freezed.dart, packages/bluesky/lib/src/entities/feed_view.g.dart, packages/bluesky/lib/src/entities/reason.dart, packages/bluesky/lib/src/entities/reason.freezed.dart, packages/bluesky/lib/src/entities/reason_repost.dart, packages/bluesky/lib/src/entities/reason_repost.freezed.dart, packages/bluesky/lib/src/entities/reason_repost.g.dart
=> fix: fixed for the issue (#399)

.vscode/settings.json, packages/atproto/lib/src/entities/blob.dart, packages/atproto/lib/src/entities/blob.freezed.dart, packages/atproto/lib/src/entities/blob.g.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/graphs/graphs_service.dart, packages/bluesky/lib/src/params/list_param.dart, packages/bluesky/lib/src/params/list_param.freezed.dart, packages/bluesky/lib/src/params/list_param.g.dart, packages/bluesky/pubspec.yaml, packages/bluesky/pubspec_overrides.yaml, packages/bluesky/test/src/graphs/data/create_list.json, packages/bluesky/test/src/graphs/graphs_service_test.dart, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/bsky_command.dart, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command/graph/list.dart
=> feat: fixed for the issue (#392)

packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/list_item.dart, packages/bluesky/lib/src/entities/list_item.freezed.dart, packages/bluesky/lib/src/entities/list_item.g.dart, packages/bluesky/lib/src/entities/list_items.dart, packages/bluesky/lib/src/entities/list_items.freezed.dart, packages/bluesky/lib/src/entities/list_items.g.dart, packages/bluesky/lib/src/graphs/graphs_service.dart, packages/bluesky/test/src/graphs/data/find_list_items.json, packages/bluesky/test/src/graphs/graphs_service_test.dart, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command/graph/list.dart
=> feat: fixed for the issue (#389)

packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/src/graphs/graphs_service.dart, packages/bluesky/test/src/graphs/data/find_muting_lists.json, packages/bluesky/test/src/graphs/graphs_service_test.dart, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command/graph/muting_lists.dart
=> feat: fixed for the issue (#390)

packages/at_identifier/CHANGELOG.md, packages/at_identifier/pubspec.yaml, packages/at_uri/CHANGELOG.md, packages/at_uri/pubspec.yaml, packages/atproto/CHANGELOG.md, packages/atproto/pubspec.yaml, packages/atproto/pubspec_overrides.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/pubspec.yaml, packages/atproto_test/CHANGELOG.md, packages/atproto_test/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/bluesky/pubspec_overrides.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/pubspec_overrides.yaml, packages/lexicon/pubspec.yaml, packages/nsid/CHANGELOG.md, packages/nsid/pubspec.yaml, packages/xrpc/CHANGELOG.md, packages/xrpc/pubspec.yaml
=> fix: fixed for the issue (#406)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/lib/src/graphs/graphs_service.dart, packages/bluesky/lib/src/params/thread_param.dart, packages/bluesky/lib/src/params/thread_param.freezed.dart, packages/bluesky/lib/src/params/thread_param.g.dart, packages/bluesky/test/src/feeds/feeds_service_test.dart, packages/bluesky/test/src/graphs/graphs_service_test.dart
=> feat: added `createThread` (#370)

packages/nsid/CHANGELOG.md
=> docs: added version

packages/bluesky/pubspec.yaml
=> fix: removed dependency

packages/bluesky_cli/pubspec.yaml
=> fix: fixed sdk

.github/workflows/auto_mirror_lexicons.yml
=> fix: added delete branch section

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/converter/preference_converter.dart, packages/bluesky/lib/src/entities/preference.dart, packages/bluesky/lib/src/entities/preference.freezed.dart, packages/bluesky/lib/src/entities/preferences.freezed.dart, packages/bluesky/lib/src/entities/saved_feeds_preference.dart, packages/bluesky/lib/src/entities/saved_feeds_preference.freezed.dart, packages/bluesky/lib/src/entities/saved_feeds_preference.g.dart, packages/bluesky/test/src/actors/data/find_preferences.json
=> feat: fixed for the issue (#427)

packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/test/src/feeds/data/find_custom_feed.json, packages/bluesky/test/src/feeds/feeds_service_test.dart, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command/feed/custom_feed.dart
=> feat: `app.bsky.feed.getFeed` (#432)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/converter/embed_view_record_view_converter.dart, packages/bluesky/lib/src/entities/embed_view_record.freezed.dart, packages/bluesky/lib/src/entities/embed_view_record_view.dart, packages/bluesky/lib/src/entities/embed_view_record_view.freezed.dart, packages/bluesky/test/src/feeds/data/find_home_timeline.json
=> feat: `app.bsky.feed.defs#generatorView` (#428)

.github/scripts/check-release.sh
=> fix: fixed to get folder name from tag

.github/workflows/auto_update_examples_index.yml
=> fix: fixed commit message

packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/feeds/feeds_service_test.dart
=> fix: renamed (#456)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/test/src/feeds/feeds_service_test.dart
=> feat: added `parentHeight` (#457)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/identities/identities_service.dart, packages/atproto/pubspec.yaml, packages/bluesky/pubspec.yaml
=> fix: fixed for the issue (#459)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/unspecced/unspecced_service.dart, packages/bluesky/test/src/unspecced/data/find_popular_feed_generators.json, packages/bluesky/test/src/unspecced/unspecced_service_test.dart, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command/unspecced/popular_generators.dart, packages/bluesky_cli/lib/src/version.g.dart, packages/bluesky_cli/pubspec.yaml
=> feat: `unspecced.getPopularFeedGenerators` (#458)

packages/bluesky/lib/src/entities/post_thread_view_record.dart
=> fix: fixed pass static analysis

.vscode/settings.json, packages/multiformats/CHANGELOG.md, packages/multiformats/README.md, packages/multiformats/example/example.dart, packages/multiformats/lib/src/base32.dart, packages/multiformats/lib/src/cid.dart, packages/multiformats/pubspec.yaml, packages/multiformats/test/src/cid_test.dart
=> feat: added `CID.create` (#477)

packages/multiformats/CHANGELOG.md, packages/multiformats/lib/src/cid.dart, packages/multiformats/test/src/cid_test.dart
=> feat: Added validation in `CID.parse` (#479)

packages/multiformats/CHANGELOG.md, packages/multiformats/lib/src/cid.dart, packages/multiformats/pubspec.yaml, packages/multiformats/test/src/cid_test.dart
=> fix: fixed for the issue (#482)

.vscode/settings.json, packages/multiformats/CHANGELOG.md, packages/multiformats/lib/src/cid.dart, packages/multiformats/pubspec.yaml, packages/multiformats/test/src/cid_test.dart
=> feat: supported `dag-cbor` (#484)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/converter/subscribe_repo_updates_converter.dart
=> fix: fixed for the issue (#487)

migrate/DISCLAIMER.md, migrate/atproto/v0.4.0.md, migrate/bluesky/v0.6.0.md
=> docs: added migrations (#516)

migrate/bluesky/v0.6.0.md
=> docs: added links

packages/bluesky_post/lib/post.dart, packages/bluesky_post/pubspec.yaml
=> fix: fixed dependency

packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/pubspec.yaml
=> fix: upgraded dependencies

website/src/components/Banner/index.tsx
=> fix: fixed broken link (#524)

website/docusaurus.config.js, website/src/pages/index.js, website/src/pages/showcase/index.tsx
=> fix: fixed website (#526)

website/src/components/Banner/index.tsx
=> fix: removed github star (#527)

README.md
=> feat: add netlify badge (#528)

website/src/components/Banner/style.scss
=> fix: fixed banner url (#532)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/lib/src/params/post_param.dart, packages/bluesky/lib/src/params/post_param.freezed.dart, packages/bluesky/lib/src/params/post_param.g.dart, packages/bluesky/lib/src/params/thread_param.dart, packages/bluesky/lib/src/params/thread_param.freezed.dart, packages/bluesky/lib/src/params/thread_param.g.dart, packages/bluesky/pubspec.yaml
=> feat: supported `langs` parameter (#538)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/list_view.dart, packages/bluesky/lib/src/entities/list_view.freezed.dart, packages/bluesky/lib/src/entities/list_view.g.dart, packages/bluesky/lib/src/entities/list_view_basic.dart, packages/bluesky/lib/src/entities/list_view_basic.freezed.dart, packages/bluesky/lib/src/entities/list_view_basic.g.dart, packages/bluesky/test/src/graphs/data/find_list_items.json, packages/bluesky/test/src/graphs/data/find_lists.json, packages/bluesky/test/src/graphs/data/find_muting_lists.json, packages/bluesky/test/src/graphs/graphs_service_test.dart
=> feat: added `cid` field (#539)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/converter/embed_view_record_view_converter.dart, packages/bluesky/lib/src/entities/embed_view_record_view.dart, packages/bluesky/lib/src/entities/embed_view_record_view.freezed.dart, packages/bluesky/lib/src/entities/list_view.dart, packages/bluesky/lib/src/entities/list_view.freezed.dart, packages/bluesky/lib/src/entities/list_view.g.dart, packages/bluesky/lib/src/entities/list_view_basic.dart, packages/bluesky/lib/src/entities/list_view_basic.freezed.dart, packages/bluesky/lib/src/entities/list_view_basic.g.dart, packages/bluesky/test/src/feeds/data/find_home_timeline.json
=> feat: added union field (#540)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/actor.dart, packages/bluesky/lib/src/entities/actor.freezed.dart, packages/bluesky/lib/src/entities/actor_profile.dart, packages/bluesky/lib/src/entities/actor_profile.freezed.dart, packages/bluesky/lib/src/entities/actor_viewer.dart, packages/bluesky/lib/src/entities/actor_viewer.freezed.dart, packages/bluesky/lib/src/entities/post.dart, packages/bluesky/lib/src/entities/post_viewer.dart, packages/bluesky/lib/src/entities/post_viewer.freezed.dart
=> feat: added useful methods (#546)

packages/atproto/CHANGELOG.md, packages/atproto/lib/atproto.dart, packages/atproto/lib/src/repositories/repositories_service.dart, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/atproto_core.dart, packages/atproto_core/lib/src/base_service.dart, packages/atproto_core/lib/src/client/anonymous_client.dart, packages/atproto_core/lib/src/client/auth_required_client.dart, packages/atproto_core/lib/src/client/challenge.dart, packages/atproto_core/lib/src/client/client.dart, packages/atproto_core/lib/src/client/client_context.dart, packages/atproto_core/pubspec.yaml, packages/atproto_test/CHANGELOG.md, packages/atproto_test/lib/src/mocks/mocked_clients.dart, packages/atproto_test/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/pubspec.yaml, packages/bluesky_post/lib/post.dart, packages/xrpc/CHANGELOG.md, packages/xrpc/lib/src/xrpc.dart, packages/xrpc/lib/xrpc.dart, packages/xrpc/pubspec.yaml
=> fix: exposed objects from `universal_io` (#541)

.github/workflows/upgrade_dependencies.yml
=> fix: removed `--null-safety`

.github/workflows/dependency_check.yml, bin/validate_dependencies.dart, packages/atproto/lib/atproto.dart, packages/atproto/lib/src/repositories/repositories_service.dart, packages/atproto/pubspec.yaml, packages/atproto_core/lib/atproto_core.dart, packages/atproto_core/lib/src/base_service.dart, packages/atproto_core/lib/src/client/anonymous_client.dart, packages/atproto_core/lib/src/client/auth_required_client.dart, packages/atproto_core/lib/src/client/challenge.dart, packages/atproto_core/lib/src/client/client.dart, packages/atproto_core/lib/src/client/client_context.dart, packages/atproto_core/pubspec.yaml, packages/atproto_test/lib/src/mocks/mocked_clients.dart, packages/atproto_test/pubspec.yaml, packages/bluesky/lib/bluesky.dart, packages/bluesky_post/lib/post.dart, packages/xrpc/lib/xrpc.dart, packages/xrpc/pubspec.yaml, pubspec.yaml
=> fix: fixed for the issue (#551)

packages/multiformats/pubspec.yaml
=> fix: fixed to use `dart_multihash` v0.2.1 (#552)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/repositories/repositories_service.dart, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/base_service.dart, packages/atproto_core/lib/src/client/anonymous_client.dart, packages/atproto_core/lib/src/client/auth_required_client.dart, packages/atproto_core/lib/src/client/client.dart, packages/atproto_core/lib/src/client/client_context.dart, packages/atproto_core/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/bluesky_cards/pubspec.yaml, packages/bluesky_cli/lib/src/command/bsky_command.dart, packages/bluesky_post/lib/post.dart, packages/bluesky_text/pubspec.yaml, packages/xrpc/CHANGELOG.md, packages/xrpc/example/example.dart, packages/xrpc/lib/src/xrpc.dart, packages/xrpc/pubspec.yaml
=> fix: fixed for the issue (#556)

bin/validate_dependencies.dart, packages/bluesky_cards/CHANGELOG.md, packages/bluesky_cards/pubspec.yaml, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/pubspec.yaml, packages/multiformats/pubspec.yaml
=> fix: fixed dependencies (#558)

packages/bluesky/lib/src/bluesky_base_service.dart, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/lib/src/graphs/graphs_service.dart, packages/bluesky/lib/src/notifications/notifications_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/feeds/feeds_service_test.dart, packages/bluesky_cards/CHANGELOG.md, packages/bluesky_cards/pubspec.yaml
=> refactor: standardize internal process (#559)

bin/release/publish_all.dart
=> fix: improved auto publish (#570)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/actor.dart, packages/bluesky/lib/src/entities/actor_profile.dart, packages/bluesky/lib/src/entities/actor_viewer.dart, packages/bluesky/lib/src/entities/list_view.dart, packages/bluesky/lib/src/entities/list_view.freezed.dart, packages/bluesky/lib/src/entities/list_view_basic.dart, packages/bluesky/lib/src/entities/list_view_basic.freezed.dart, packages/bluesky/lib/src/entities/list_viewer.dart, packages/bluesky/lib/src/entities/list_viewer.freezed.dart, packages/bluesky/test/src/entities/actor_profile_test.dart, packages/bluesky/test/src/entities/actor_test.dart, packages/bluesky/test/src/entities/list_view_basic_test.dart, packages/bluesky/test/src/entities/list_view_test.dart, packages/bluesky/test/src/entities/post_test.dart
=> feat: add viewer utilities (#576)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/feed_generators.dart, packages/bluesky/lib/src/entities/feed_generators.freezed.dart, packages/bluesky/lib/src/entities/feed_generators.g.dart, packages/bluesky/lib/src/unspecced/unspecced_service.dart, packages/bluesky/test/src/unspecced/data/find_popular_feed_generators.json
=> feat: added input and output (#581)

packages/atproto_core/test/src/converter/at_uri_converter_test.dart, packages/atproto_core/test/src/progress_status_test.dart, packages/xrpc/test/src/exception/xrpc_exception_test.dart, packages/xrpc/test/src/xrpc_request_test.dart, packages/xrpc/test/src/xrpc_response_test.dart, packages/xrpc/test/src/xrpc_test.dart
=> test: added unit tests

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/repositories/repositories_service.dart, packages/atproto/lib/src/sync/sync_service.dart, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/base_service.dart, packages/atproto_core/lib/src/client/anonymous_client.dart, packages/atproto_core/pubspec.yaml, packages/atproto_core/test/src/base_service_test.dart, packages/atproto_core/test/src/client/retry_policy_test.dart, packages/atproto_test/lib/src/mocks/mocked_clients.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/bluesky_cards/CHANGELOG.md, packages/bluesky_cards/pubspec.yaml
=> test: add unit tests

packages/atproto/test/src/atproto_test.dart, packages/bluesky/test/src/bluesky_test.dart
=> test: added unit test

README.md
=> docs: added publish commands

README.md
=> docs: removed outdated note

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/extension/blob_extension.dart, packages/bluesky/test/src/extension/blob_extension_test.dart
=> ✨ feat: added blob utilities (#604)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/extension/strong_ref_extension.dart, packages/bluesky/test/src/extension/strong_ref_extension_test.dart
=> ✨ feat: added StrongRef utilities (#607)

packages/at_identifier/pubspec.yaml, packages/at_uri/pubspec.yaml, packages/atproto/pubspec.yaml, packages/atproto_core/pubspec.yaml, packages/bluesky/pubspec.yaml, packages/bluesky_cards/pubspec.yaml, packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/pubspec.yaml, packages/multiformats/pubspec.yaml, packages/nsid/pubspec.yaml, packages/xrpc/pubspec.yaml
=> ✨ feat: added `topics` (#601)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/lib/src/unspecced/unspecced_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/unspecced/unspecced_service_test.dart, packages/bluesky_cards/CHANGELOG.md, packages/bluesky_cards/pubspec.yaml
=> ✨ feat: added `query` parameters (#615)

packages/atproto_core/lib/atproto_core.dart, packages/atproto_core/lib/src/const.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/lib/src/graphs/graphs_service.dart, packages/bluesky/lib/src/params/generator_param.dart, packages/bluesky/lib/src/params/generator_param.freezed.dart, packages/bluesky/lib/src/params/generator_param.g.dart, packages/bluesky/lib/src/params/list_item_param.dart, packages/bluesky/lib/src/params/list_item_param.freezed.dart, packages/bluesky/lib/src/params/list_item_param.g.dart, packages/bluesky/lib/src/params/list_param.dart, packages/bluesky/lib/src/params/list_param.freezed.dart, packages/bluesky/lib/src/params/list_param.g.dart, packages/bluesky/lib/src/params/post_param.dart, packages/bluesky/lib/src/params/post_param.freezed.dart, packages/bluesky/lib/src/params/post_param.g.dart, packages/bluesky/lib/src/params/repo_param.dart, packages/bluesky/lib/src/params/repo_param.freezed.dart, packages/bluesky/lib/src/params/repo_param.g.dart, packages/bluesky/lib/src/params/strong_ref_param.dart, packages/bluesky/lib/src/params/strong_ref_param.freezed.dart, packages/bluesky/lib/src/params/strong_ref_param.g.dart, packages/bluesky/lib/src/params/thread_param.dart, packages/bluesky/lib/src/params/thread_param.freezed.dart, packages/bluesky/lib/src/params/thread_param.g.dart
=> ✨ feat: added `unspecced` parameter (#612)

README.md, melos.yaml
=> ✨ feat: added `publish_all` command (#598)

.github/workflows/auto_mirror_lexicons.yml, bin/generate_lexicon_ids.dart, packages/atproto/lib/src/entities/keys/ids.g.dart, packages/bluesky/lib/src/entities/keys/ids.g.dart
=> 🚀  refactor: sort lexicon ids asc (#624)

packages/atproto/CHANGELOG.md, packages/atproto/lib/ids.dart, packages/atproto/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/ids.dart, packages/bluesky/pubspec.yaml, packages/bluesky_cards/CHANGELOG.md, packages/bluesky_cards/pubspec.yaml, website/docs/packages/atproto.md, website/docs/packages/bluesky.md
=> ✨ feat: exposed lexicon ids (#623)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/entities/repos.dart, packages/atproto/lib/src/entities/repos.freezed.dart, packages/atproto/lib/src/entities/repos.g.dart, packages/atproto/pubspec.yaml, packages/atproto/test/src/sync/data/find_repos.json, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/bluesky_cards/CHANGELOG.md, packages/bluesky_cards/pubspec.yaml
=> ✨ feat: added `cursor` parameter (#627)

website/docs/packages/bluesky.md
=> 📖 docs: fixed typos

website/docs/packages/atproto.md, website/docs/packages/bluesky.md, website/docs/packages/bluesky_text.md
=> 📖 docs: added doc for `bluesky_text` (#630)

website/docs/packages/bluesky_text.md
=> 👌 fix: fixed doc link (#635)

packages/xrpc/CHANGELOG.md, packages/xrpc/lib/src/entities/rate_limit.dart, packages/xrpc/pubspec.yaml, packages/xrpc/test/src/entities/rate_limit_test.dart, website/docs/packages/atproto.md, website/docs/packages/bluesky.md
=> 🚀 feat: added `.waitUntilReset` (#643)

README.md, melos.yaml
=> ✨ feat: added `melos build_runner` command (#641)

.github/workflows/auto_mirror_lexicons.yml
=> feat: added activation

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/feeds/feed_filter.dart, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/feeds/feed_filter_test.dart, packages/bluesky_cards/pubspec.yaml
=> 🚀 feat: added `filter` parameter (#655)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/actor_viewer.dart, packages/bluesky/lib/src/entities/actor_viewer.freezed.dart, packages/bluesky/lib/src/entities/actor_viewer.g.dart, packages/bluesky/lib/src/entities/blocked_author.dart, packages/bluesky/lib/src/entities/blocked_author.freezed.dart, packages/bluesky/lib/src/entities/blocked_author.g.dart, packages/bluesky/lib/src/entities/blocked_post.dart, packages/bluesky/lib/src/entities/blocked_post.freezed.dart, packages/bluesky/lib/src/entities/blocked_post.g.dart, packages/bluesky/lib/src/entities/embed_view_record_view_blocked.dart, packages/bluesky/lib/src/entities/embed_view_record_view_blocked.freezed.dart, packages/bluesky/lib/src/entities/embed_view_record_view_blocked.g.dart, packages/bluesky/lib/src/entities/embed_view_record_view_not_found.dart, packages/bluesky/lib/src/entities/embed_view_record_view_not_found.freezed.dart, packages/bluesky/lib/src/entities/embed_view_record_view_not_found.g.dart, packages/bluesky/lib/src/entities/keys/ids.g.dart, packages/bluesky/lib/src/entities/list_viewer.dart, packages/bluesky/lib/src/entities/list_viewer.freezed.dart, packages/bluesky/lib/src/entities/list_viewer.g.dart, packages/bluesky/lib/src/entities/not_found_post.dart, packages/bluesky/lib/src/entities/not_found_post.freezed.dart, packages/bluesky/lib/src/entities/not_found_post.g.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/feeds/data/find_home_timeline.json, packages/bluesky/test/src/feeds/data/find_post_thread.json, packages/bluesky_cards/pubspec.yaml
=> ✨ feat: supported `blocked_author` (#660)

packages/at_identifier/CHANGELOG.md, packages/at_identifier/pubspec.yaml, packages/at_uri/CHANGELOG.md, packages/at_uri/pubspec.yaml, packages/atproto/CHANGELOG.md, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/pubspec.yaml, packages/atproto_test/CHANGELOG.md, packages/atproto_test/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/bluesky_cards/CHANGELOG.md, packages/bluesky_cards/pubspec.yaml, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/pubspec.yaml, packages/lexicon/pubspec.yaml, packages/multiformats/CHANGELOG.md, packages/multiformats/pubspec.yaml, packages/nsid/CHANGELOG.md, packages/nsid/pubspec.yaml, packages/xrpc/CHANGELOG.md, packages/xrpc/pubspec.yaml
=> 🎉 feat: bump up `^3.0.0` (#599)

packages/bluesky_cli/pubspec_overrides.yaml
=> 🔧  fix: added overrides

website/docs/packages/bluesky.md
=> 📖 docs: fix typos

packages/bluesky_post/CHANGELOG.md, packages/bluesky_post/README.md, packages/bluesky_post/action.yaml, packages/bluesky_post/lib/post.dart, packages/bluesky_post/pubspec.yaml
=> 🚀  feat: added `langs` and `labels` params (#668)

packages/bluesky_post/README.md
=> 📖  docs: fixed typos

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/unspecced/unspecced_service.dart, packages/bluesky/test/src/unspecced/data/find_timeline_skeleton.json, packages/bluesky/test/src/unspecced/unspecced_service_test.dart, website/docs/api_support_matrix.md
=> ✨ feat: supported `getTimelineSkeleton` (#573)

README.md, packages/atproto/CHANGELOG.md, packages/atproto/README.md, packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/README.md, packages/bluesky_text/pubspec.yaml
=> 📖 docs: imporoved docs (#677)

.github/workflows/auto_mirror_lexicons.yml
=> fix: change schedule

melos.yaml, packages/at_uri/CHANGELOG.md, packages/at_uri/README.md, packages/at_uri/pubspec.yaml, packages/atproto/CHANGELOG.md, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command/feed/post.dart, packages/bluesky_cli/lib/src/command/feed/posts.dart, packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/pubspec.yaml, packages/multiformats/CHANGELOG.md, packages/multiformats/README.md, packages/multiformats/pubspec.yaml, packages/nsid/CHANGELOG.md, packages/nsid/README.md, packages/nsid/pubspec.yaml, packages/xrpc/CHANGELOG.md, packages/xrpc/README.md, packages/xrpc/pubspec.yaml, website/docs/api_support_matrix.md
=> ✨ feat: added `posts`, `langs`, `lebales` (#679)

website/docs/packages/atproto.md, website/docs/packages/bluesky.md
=> 📖 docs: added `Session Management` (#687)

packages/bluesky/CHANGELOG.md
=> 📖 docs: added changelog

.github/workflows/auto_mirror_lexicons.yml
=> changed schedule

website/docs/packages/atproto.md, website/docs/packages/bluesky.md
=> 📖 docs: fixed typos (#695)

website/src/data/users.tsx
=> ✨ refactor: apply oss tag (#704)

website/docusaurus.config.js
=> 📖 docs: added algolia (#711)

website/docusaurus.config.js
=> docs: removed

packages/atproto/CHANGELOG.md, packages/atproto/README.md, packages/atproto/lib/atproto.dart, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/atproto_core.dart, packages/atproto_core/lib/src/utils.dart, packages/atproto_core/test/utils_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, website/docs/packages/atproto.md, website/docs/packages/bluesky.md
=> ✨ feat: added `isValidAppPassword` (#713)

.github/ISSUE_TEMPLATE/00_bug.md, .github/ISSUE_TEMPLATE/01_feature.md, .github/ISSUE_TEMPLATE/02_improvement.md, .github/ISSUE_TEMPLATE/03_showcase.md, .github/ISSUE_TEMPLATE/04_question.md, .github/pull_request_template.md
=> 📖 docs: revamped templates (#722)

.github/pull_request_template.md, packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/bluesky_text.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> 🐛 fix: fixed range error (#734)

bin/validate_dependencies.dart
=> excluded `bluesky_cards`

packages/bluesky/CHANGELOG.md
=> 📖 docs: updated changelog

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/grouped_notification.dart, packages/bluesky/lib/src/entities/grouped_notification.freezed.dart, packages/bluesky/lib/src/entities/grouped_notification.g.dart, packages/bluesky/lib/src/notifications/notifications_grouper.dart, packages/bluesky/pubspec.yaml
=> 🔧 fix: `reasonSubject` is nullable (#743)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/grouped_notification.dart, packages/bluesky/lib/src/entities/grouped_notification.freezed.dart, packages/bluesky/lib/src/entities/grouped_notification.g.dart, packages/bluesky/lib/src/entities/notification.dart, packages/bluesky/lib/src/entities/notifications.dart, packages/bluesky/lib/src/notifications/grouped_notification_reason.dart, packages/bluesky/lib/src/notifications/notification_reason.dart, packages/bluesky/lib/src/notifications/notifications_grouper.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/notifications/data/find_notifications.json, packages/bluesky/test/src/notifications/grouped_notification_reason.dart, packages/bluesky/test/src/notifications/notification_reason_test.dart, packages/bluesky/test/src/notifications/notifications_grouper_test.dart, packages/bluesky/test/src/notifications/notifications_service_test.dart
=> ✨feat: improve suggestion grouping of notifications (#745)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/grouped_notification.dart, packages/bluesky/lib/src/entities/grouped_notification.freezed.dart, packages/bluesky/lib/src/entities/grouped_notification.g.dart, packages/bluesky/lib/src/extension/grouped_notification_extension.dart, packages/bluesky/lib/src/notifications/notifications_grouper.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/extension/grouped_notification_extension_test.dart, packages/bluesky/test/src/notifications/notifications_grouper_test.dart
=> feat: add uri field on GroupedNotification (#747)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/grouped_notification.dart, packages/bluesky/lib/src/entities/grouped_notification.freezed.dart, packages/bluesky/lib/src/entities/grouped_notification.g.dart, packages/bluesky/lib/src/notifications/notifications_grouper.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/notifications/notifications_grouper_test.dart
=> feat: add uri field on GroupedNotification

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/image.dart, packages/bluesky/lib/src/entities/image.freezed.dart, packages/bluesky/lib/src/entities/image.g.dart, packages/bluesky/lib/src/entities/image_aspect_ratio.dart, packages/bluesky/lib/src/entities/image_aspect_ratio.freezed.dart, packages/bluesky/lib/src/entities/image_aspect_ratio.g.dart, packages/bluesky/lib/src/extension/blob_extension.dart, packages/bluesky/test/src/feeds/data/find_home_timeline.json
=> feat: supported aspect ratio (#753)

packages/bluesky_text/example/example.dart
=> fix example

packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/bluesky_text.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> fix: fixed bug `bluesky_text`

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/converter/preference_converter.dart, packages/bluesky/lib/src/entities/personal_details_preference.dart, packages/bluesky/lib/src/entities/personal_details_preference.freezed.dart, packages/bluesky/lib/src/entities/personal_details_preference.g.dart, packages/bluesky/lib/src/entities/preference.dart, packages/bluesky/lib/src/entities/preference.freezed.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/actors/actors_service_test.dart, packages/bluesky/test/src/actors/data/find_preferences.json
=> ✨ feat: added `.personalDetailsPref` (#768)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/adaptor/repo_commit_create.dart, packages/bluesky/lib/src/entities/adaptor/repo_commit_update.dart, packages/bluesky/test/src/entities/adaptor/repo_commit_create_test.dart, packages/bluesky/test/src/entities/adaptor/repo_commit_update_test.dart
=> ✨ feat: added `.toStrongRef` (#771)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/entities/converter/labels_converter.dart, packages/atproto/lib/src/entities/converter/report_subject_converter.dart, packages/atproto/lib/src/entities/converter/subscribed_repo_converter.dart, packages/atproto/lib/src/moderation/moderation_reason_type.dart, packages/atproto/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/converter/embed_converter.dart, packages/bluesky/lib/src/entities/converter/embed_media_converter.dart, packages/bluesky/lib/src/entities/converter/embed_view_converter.dart, packages/bluesky/lib/src/entities/converter/embed_view_media_converter.dart, packages/bluesky/lib/src/entities/converter/embed_view_record_view_converter.dart, packages/bluesky/lib/src/entities/converter/facet_feature_converter.dart, packages/bluesky/lib/src/entities/converter/post_thread_view_converter.dart, packages/bluesky/lib/src/entities/converter/preference_converter.dart, packages/bluesky/lib/src/entities/converter/reason_converter.dart, packages/bluesky/lib/src/entities/converter/reply_post_converter.dart, packages/bluesky/lib/src/entities/converter/skeleton_reason_converter.dart, packages/bluesky/pubspec.yaml
=> 🔧 fix: safe conversion for union (#775)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/actor.dart, packages/bluesky/lib/src/entities/actor.freezed.dart, packages/bluesky/lib/src/entities/actor.g.dart, packages/bluesky/pubspec.yaml
=> fix!: `viewer` is nullable (#779)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/list_view.dart, packages/bluesky/lib/src/entities/list_view_basic.dart, packages/bluesky/lib/src/entities/list_viewer.dart, packages/bluesky/lib/src/entities/list_viewer.freezed.dart, packages/bluesky/lib/src/entities/list_viewer.g.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/entities/list_view_basic_test.dart, packages/bluesky/test/src/entities/list_view_test.dart
=> ✨ feat: added `blocked` property (#792)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/test/src/feeds/data/find_list_feed.json, packages/bluesky/test/src/feeds/feeds_service_test.dart, packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/README.md, packages/bluesky_cli/example/README.md, packages/bluesky_cli/lib/src/command/commands.dart, packages/bluesky_cli/lib/src/command/feed/list_feed.dart, packages/bluesky_cli/lib/src/version.g.dart, packages/bluesky_cli/pubspec.yaml, website/docs/api_support_matrix.md
=> 🎉 feat: find list feed (#813)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/notifications.dart, packages/bluesky/lib/src/notifications/group_by.dart, packages/bluesky/lib/src/notifications/notifications_grouper.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/notifications/notifications_grouper_test.dart
=> 🚀 feat: group by hour or minute (#821)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/notifications.dart, packages/bluesky/lib/src/notifications/group_by.dart, packages/bluesky/lib/src/notifications/notification_reason_filter.dart, packages/bluesky/lib/src/notifications/notifications_grouper.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/notifications/notification_reason_filter_test.dart, packages/bluesky/test/src/notifications/notifications_grouper_test.dart
=> ✨ feat!: notification reason filter (#826)

.vscode/settings.json, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/converter/preference_converter.dart, packages/bluesky/lib/src/entities/feed_view_preference.dart, packages/bluesky/lib/src/entities/feed_view_preference.freezed.dart, packages/bluesky/lib/src/entities/feed_view_preference.g.dart, packages/bluesky/lib/src/entities/preference.dart, packages/bluesky/lib/src/entities/preference.freezed.dart, packages/bluesky/lib/src/entities/thread_view_preference.dart, packages/bluesky/lib/src/entities/thread_view_preference.freezed.dart, packages/bluesky/lib/src/entities/thread_view_preference.g.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/actors/actors_service_test.dart, packages/bluesky/test/src/actors/data/find_preferences.json
=> ✨ feat: actor preferences (#831)

packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/example/example.dart, packages/bluesky_text/lib/bluesky_text.dart, packages/bluesky_text/lib/src/bluesky_text.dart, packages/bluesky_text/lib/src/config/link_config.dart, packages/bluesky_text/lib/src/replacement.dart, packages/bluesky_text/test/config/link_config_test.dart, packages/bluesky_text/test/src/bluesky_text_test.dart, website/docs/packages/bluesky_text.md
=> 🚀 feat: link config (#832)

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/bluesky_text.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> 🔧 fix: `.format()`

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/unspecced/unspecced_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/unspecced/unspecced_service_test.dart
=> 🔧 fix: deprecate (#835)

packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/sessions/session.dart, packages/atproto_core/lib/src/sessions/session.freezed.dart, packages/atproto_core/lib/src/sessions/session.g.dart, packages/atproto_core/pubspec.yaml, packages/atproto_core/test/src/sessions/data/create_session.json, packages/atproto_core/test/src/sessions/sessions_test.dart, packages/bluesky/pubspec.yaml, packages/bluesky_text/pubspec_overrides.yaml
=> ✨ feat: added `emailConfirmed` (#856)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/entities/current_session.dart, packages/atproto/lib/src/entities/current_session.freezed.dart, packages/atproto/lib/src/entities/current_session.g.dart, packages/atproto/test/src/servers/data/find_current_session.json, packages/atproto/test/src/servers/servers_service_test.dart
=> 👌 feat: added `emailConfirmed` (#857)

packages/atproto/CHANGELOG.md, packages/atproto/lib/atproto.dart, packages/atproto/lib/src/entities/email_update.dart, packages/atproto/lib/src/entities/email_update.freezed.dart, packages/atproto/lib/src/entities/email_update.g.dart, packages/atproto/lib/src/servers/servers_service.dart, packages/atproto/test/src/servers/data/request_email_update.json, packages/atproto/test/src/servers/servers_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, website/docs/api_support_matrix.md
=> ✨ feat: supported `requestEmailUpdate` (#859)

.vscode/settings.json, packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/bluesky_text.dart, packages/bluesky_text/lib/src/regex/cyrillic_letters_and_marks.dart, packages/bluesky_text/lib/src/regex/directional_markers_group.dart, packages/bluesky_text/lib/src/regex/extract_url.dart, packages/bluesky_text/lib/src/regex/invalid_chars_group.dart, packages/bluesky_text/lib/src/regex/invalid_domain_chars.dart, packages/bluesky_text/lib/src/regex/latin_accent_chars.dart, packages/bluesky_text/lib/src/regex/punc.dart, packages/bluesky_text/lib/src/regex/spaces_group.dart, packages/bluesky_text/lib/src/regex/valid_ashii_domain.dart, packages/bluesky_text/lib/src/regex/valid_cctld.dart, packages/bluesky_text/lib/src/regex/valid_domain.dart, packages/bluesky_text/lib/src/regex/valid_domain_chars.dart, packages/bluesky_text/lib/src/regex/valid_domain_name.dart, packages/bluesky_text/lib/src/regex/valid_general_url_path_chars.dart, packages/bluesky_text/lib/src/regex/valid_port_number.dart, packages/bluesky_text/lib/src/regex/valid_subdomain.dart, packages/bluesky_text/lib/src/regex/valid_url_balanced_parens.dart, packages/bluesky_text/lib/src/regex/valid_url_path_ending_chars.dart, packages/bluesky_text/lib/src/regex/valid_url_query_chars.dart, packages/bluesky_text/lib/src/regex/valid_url_query_ending_chars.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> 🎉 refactor: better link detection (#870)

packages/bluesky_text/README.md, website/docs/packages/bluesky_text.md
=> 📖 docs: added feature things (#871)

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/bluesky_text.dart, packages/bluesky_text/lib/src/extractor.dart, packages/bluesky_text/lib/src/formatter.dart, packages/bluesky_text/lib/src/regex/extract_url.dart, packages/bluesky_text/lib/src/regex/valid_ascii_domain.dart, packages/bluesky_text/lib/src/replacement.dart, packages/bluesky_text/lib/src/unicode_string.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> 🔧 refactor: better format

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/README.md, packages/bluesky_text/lib/src/bluesky_text.dart, packages/bluesky_text/lib/src/entities/entity.dart, packages/bluesky_text/lib/src/entities/entity.g.dart, packages/bluesky_text/lib/src/entities/facetable.dart, packages/bluesky_text/lib/src/entities/markdown/markdown_link_entity.dart, packages/bluesky_text/lib/src/entities/markdown/markdown_link_entity.freezed.dart, packages/bluesky_text/lib/src/entities/markdown/markdown_link_entity.g.dart, packages/bluesky_text/lib/src/extractor.dart, packages/bluesky_text/lib/src/formatter.dart, packages/bluesky_text/lib/src/markdown_extractor.dart, packages/bluesky_text/lib/src/regex/markdown_link.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart, website/docs/packages/bluesky_text.md
=> ✨ feat: support markdown links (#629)

packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/lib/src/command/feed/post.dart, packages/bluesky_cli/pubspec.yaml
=> ✨ feat: supported `images` option (#825)

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/formatter.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> 🔧 fix: remove unnecessary `/` (#876)

packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/markdown_extractor.dart, packages/bluesky_text/test/src/bluesky_text_test.dart
=> 🔧 fix: allow only `http|https` (#877)

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/entities/entity.dart, packages/bluesky_text/lib/src/entities/markdown/markdown_link_entity.dart, packages/bluesky_text/lib/src/entities/markdown/markdown_link_entity.freezed.dart, packages/bluesky_text/lib/src/extractor.dart, packages/bluesky_text/lib/src/formatter.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart, packages/bluesky_text/test/src/entities/entity_test.dart
=> ✨ refactor: better markdown detection

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/entities/markdown/markdown_link_entity.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> 🐛 fix: better markdown detection

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/bluesky_text.dart, packages/bluesky_text/lib/src/entities/entity.g.dart, packages/bluesky_text/lib/src/extractor.dart, packages/bluesky_text/lib/src/formatter.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> ✨ feat: added `enableMarkdown`

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/markdown_extractor.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> ✨ fix: better markdown url

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/extractor.dart, packages/bluesky_text/lib/src/markdown_extractor.dart, packages/bluesky_text/lib/src/utils.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> 🔧 fix: prefixed markdown url

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/extractor.dart, packages/bluesky_text/lib/src/formatter.dart, packages/bluesky_text/lib/src/regex/at_signs.dart, packages/bluesky_text/lib/src/regex/valid_mention.dart, packages/bluesky_text/lib/src/regex/valid_mention_preceding_chars.dart, packages/bluesky_text/lib/src/regex/valid_url.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> ✨ feat: better handle extraction (#892)

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/markdown_extractor.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> ✨ fix: better markdown detection (#894) (#895)

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/markdown_extractor.dart, packages/bluesky_text/lib/src/regex/markdown_link.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> ✨ feat: better markdown extraction (#901)

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/bluesky_text.dart, packages/bluesky_text/lib/src/extractor/markdown_extractor.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> better markdown algo

.vscode/settings.json, packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/regex/hashtag_concat_chars.dart, packages/bluesky_text/lib/src/regex/hashtag_special_chars.dart, packages/bluesky_text/lib/src/regex/valid_hashtag.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> ✨ feat: hashtag with hyphen (#908)

lexicons/app/bsky/bookmark/add.json, lexicons/app/bsky/bookmark/defs.json, lexicons/app/bsky/bookmark/delete.json, lexicons/app/bsky/bookmark/get.json, lexicons/app/bsky/bookmark/list.json, packages/bluesky/lib/src/entities/keys/ids.g.dart
=> added bookmark lexicons

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/regex/emoji.dart, packages/bluesky_text/lib/src/regex/hashtag_alpha_numeric.dart, packages/bluesky_text/lib/src/regex/valid_hashtag.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> 🎉 feat: emojitag

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/bluesky_text.dart, packages/bluesky_text/lib/src/bluesky_text.dart, packages/bluesky_text/lib/src/utils.dart, packages/bluesky_text/pubspec.yaml
=> exposed `isEmojiOnly` as a function

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/actors/actors_service.dart
=> use recommended `q` (#849)

packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/lib/src/command/actor/actors_typeahead.dart, packages/bluesky_cli/lib/src/command/actor/search_actors.dart, packages/bluesky_cli/lib/src/version.g.dart, packages/bluesky_cli/pubspec.yaml
=> use recommended `q`

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/graphs/graphs_service.dart, packages/bluesky/test/src/graphs/data/find_block_lists.json, packages/bluesky/test/src/graphs/graphs_service_test.dart
=> ✨ feat: supported `getListBlocks` (#793)

.vscode/settings.json, packages/atproto/test/src/sync/sync_service_test.dart, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/adaptor/repo_commit_adaptor.dart, packages/bluesky/lib/src/entities/block_list_record.dart, packages/bluesky/lib/src/entities/block_list_record.freezed.dart, packages/bluesky/lib/src/entities/block_list_record.g.dart, packages/bluesky/lib/src/extension/at_uri_extension.dart, packages/bluesky/lib/src/graphs/graphs_service.dart, packages/bluesky/test/src/entities/adaptor/repo_commit_adaptor_test.dart, packages/bluesky/test/src/extension/at_uri_extension_test.dart, packages/bluesky/test/src/graphs/data/create_block_list.json, packages/bluesky/test/src/graphs/graphs_service_test.dart, website/docs/api_support_matrix.md
=> ✨ feat: supported `listblock` (#794)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/actor.dart, packages/bluesky/lib/src/entities/actor_profile.dart, packages/bluesky/lib/src/entities/actor_viewer.dart, packages/bluesky/lib/src/entities/actor_viewer.freezed.dart, packages/bluesky/lib/src/entities/actor_viewer.g.dart, packages/bluesky/test/src/entities/actor_profile_test.dart, packages/bluesky/test/src/entities/actor_test.dart
=> ✨ feat: blockingByList (#952)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/atproto.dart, packages/atproto/test/src/atproto_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/bluesky.dart, packages/bluesky/test/src/actors/actors_service_test.dart, packages/bluesky/test/src/bluesky_test.dart, packages/bluesky/test/src/feeds/feeds_service_test.dart, packages/bluesky/test/src/graphs/graphs_service_test.dart, packages/bluesky/test/src/notifications/notifications_service_test.dart, packages/bluesky/test/src/session.dart, packages/bluesky/test/src/unspecced/unspecced_service_test.dart
=> ✨ feat: `.session` property (#961)

.github/labeler.yml, packages/atproto/CHANGELOG.md, packages/atproto/README.md, packages/atproto/lib/atproto.dart, packages/atproto/lib/src/atproto.dart, packages/atproto/lib/src/atproto_service.dart, packages/atproto/lib/src/entities/labels_by_query.dart, packages/atproto/lib/src/entities/labels_by_query.freezed.dart, packages/atproto/lib/src/entities/labels_by_query.g.dart, packages/atproto/lib/src/labels/labels_service.dart, packages/atproto/pubspec.yaml, packages/atproto/test/src/atproto_test.dart, packages/atproto/test/src/labels/data/search_labels.json, packages/atproto/test/src/labels/labels_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/bluesky.dart, packages/bluesky/lib/src/bluesky_service.dart, packages/bluesky/pubspec.yaml, website/docs/api_support_matrix.md
=> ✨ feat: LabelsService (#265)

packages/atproto/CHANGELOG.md, packages/atproto/lib/atproto.dart, packages/atproto/lib/src/entities/signing_key.dart, packages/atproto/lib/src/entities/signing_key.freezed.dart, packages/atproto/lib/src/entities/signing_key.g.dart, packages/atproto/lib/src/servers/servers_service.dart, packages/atproto/test/src/servers/data/create_signing_key.json, packages/atproto/test/src/servers/servers_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, website/docs/api_support_matrix.md
=> ✨ feat: `reserveSigningKey` (#953)

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/bluesky_text.dart, packages/bluesky_text/lib/src/bluesky_text.dart, packages/bluesky_text/lib/src/utils.dart, packages/bluesky_text/pubspec.yaml
=> ✨ feat: exposed `.getGraphemeLength` (#972)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/entities/current_session.dart, packages/atproto/lib/src/entities/current_session.freezed.dart, packages/atproto/lib/src/entities/current_session.g.dart, packages/atproto/pubspec.yaml, packages/atproto/test/src/servers/data/find_current_session.json, packages/atproto/test/src/servers/servers_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml
=> ✨ feat: added `.didDoc` (#983)

packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/lib/src/extractor/markdown_extractor.dart, packages/bluesky_text/lib/src/regex/valid_url.dart, packages/bluesky_text/pubspec.yaml, packages/bluesky_text/test/src/bluesky_text_test.dart
=> fix: improved extraction algo for markdown link

packages/atproto/CHANGELOG.md, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/base_http_service.dart, packages/atproto_core/pubspec.yaml, packages/atproto_core/test/src/base_http_base_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/pubspec.yaml, packages/did_plc/CHANGELOG.md, packages/did_plc/lib/src/plc.dart, packages/did_plc/lib/src/plc_base_service.dart, packages/did_plc/pubspec.yaml, packages/xrpc/CHANGELOG.md, packages/xrpc/lib/http.dart, packages/xrpc/lib/src/http/http.dart, packages/xrpc/pubspec.yaml, packages/xrpc/test/src/http/http_test.dart
=> ✨ feat: added http post function (#999)

packages/atproto/CHANGELOG.md, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/base_xrpc_service.dart, packages/atproto_core/lib/src/clients/auth_type.dart, packages/atproto_core/lib/src/clients/client_resolver.dart, packages/atproto_core/pubspec.yaml, packages/atproto_core/test/src/clients/auth_type_test.dart, packages/atproto_core/test/src/clients/client_resolver_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/pubspec.yaml, packages/did_plc/pubspec.yaml
=> 🐛 fix: fixed auth type scope (#1012)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/post.dart, packages/bluesky/lib/src/entities/post_viewer.dart, packages/bluesky/lib/src/entities/post_viewer.freezed.dart, packages/bluesky/lib/src/entities/post_viewer.g.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/entities/post_test.dart, packages/bluesky/test/src/feeds/data/find_posts.json, packages/bluesky/test/src/feeds/feeds_service_test.dart
=> ✨ feat: added `replyDisabled` (#1019)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/entities/legacy_facet.dart, packages/bluesky/lib/src/entities/legacy_facet.freezed.dart, packages/bluesky/lib/src/entities/legacy_facet.g.dart, packages/bluesky/lib/src/entities/post_record.dart, packages/bluesky/lib/src/entities/post_record.freezed.dart, packages/bluesky/lib/src/entities/post_record.g.dart, packages/bluesky/lib/src/entities/text_slice.dart, packages/bluesky/lib/src/entities/text_slice.freezed.dart, packages/bluesky/lib/src/entities/text_slice.g.dart, packages/bluesky/pubspec.yaml
=> ✨ feat: added `entities` (#1020)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/entities/converter/post_record_converter.dart, packages/bluesky/lib/src/entities/list_item.dart, packages/bluesky/lib/src/entities/list_item.freezed.dart, packages/bluesky/lib/src/entities/list_item.g.dart, packages/bluesky/lib/src/entities/post_record.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/graphs/data/find_list_items.json
=> ✨ feat: `uri` on `listItemView` (#1026)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/identities/identities_service.dart, packages/atproto/lib/src/repositories/repositories_service.dart, packages/atproto/lib/src/servers/servers_service.dart, packages/atproto/lib/src/sync/sync_service.dart, packages/atproto/pubspec.yaml, packages/atproto/test/src/identities/identities_service_test.dart, packages/atproto/test/src/repositories/repositories_service_test.dart, packages/atproto/test/src/servers/servers_service_test.dart, packages/atproto/test/src/sync/sync_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/actors/actors_service.dart, packages/bluesky/lib/src/feeds/feeds_service.dart, packages/bluesky/lib/src/graphs/graphs_service.dart, packages/bluesky/lib/src/notifications/notifications_service.dart, packages/bluesky/lib/src/unspecced/unspecced_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/actors/actors_service_test.dart, packages/bluesky/test/src/feeds/feeds_service_test.dart, packages/bluesky/test/src/graphs/graphs_service_test.dart, packages/bluesky/test/src/notifications/notifications_service_test.dart, packages/bluesky/test/src/unspecced/unspecced_service_test.dart
=> removed `asJson` things

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/services/entities/post.dart, packages/bluesky/lib/src/services/entities/post.freezed.dart, packages/bluesky/lib/src/services/entities/post.g.dart, packages/bluesky/lib/src/services/entities/threadgate_view.dart, packages/bluesky/lib/src/services/entities/threadgate_view.freezed.dart, packages/bluesky/lib/src/services/entities/threadgate_view.g.dart, packages/bluesky/test/src/services/suite/data/app/bsky/feed/getPosts.json
=> ✨ feat: threadgate (#1036)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/moderation/accumulator.dart, packages/bluesky/lib/src/moderation/definitions/known_label.dart, packages/bluesky/lib/src/moderation/definitions/label_definition_flag.dart, packages/bluesky/lib/src/moderation/definitions/label_groups.dart, packages/bluesky/lib/src/moderation/definitions/labels.dart, packages/bluesky/lib/src/moderation/entities/label_definition.g.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/moderation/definitions/known_label_test.dart, packages/bluesky/test/src/moderation/definitions/label_definition_flag_test.dart, packages/bluesky/test/src/moderation/definitions/label_groups_test.dart, packages/bluesky/test/src/moderation/suite/data/post_moderation_behaviors.json, packages/bluesky/test/src/moderation/suite/data/profile_moderation_behaviors.json
=> ✨ feat: `!no-unauthenticated` imperative label (#1038)

packages/atproto/test/src/services/repositories_service_test.dart, packages/atproto/test/src/services/suite/service_suite.dart, packages/atproto/test/src/services/sync_service_test.dart, packages/atproto_test/lib/src/expectations.dart, packages/bluesky/test/src/services/actors_service_test.dart, packages/bluesky/test/src/services/feeds_service_test.dart, packages/bluesky/test/src/services/graphs_service_test.dart, packages/bluesky/test/src/services/notifications_service_test.dart, packages/bluesky/test/src/services/suite/service_suite.dart, packages/bluesky/test/src/services/unspecced_service_test.dart
=> test: add unit tests (#1041)

.github/workflows/pull_latest_lexicons.yml, .github/workflows/pull_latest_mod_resources.yml
=> add options

bin/generate_mod_definitions.dart
=> add template label

.github/workflows/cicd.yml, .vscode/settings.json, README.md, melos.yaml
=> refactor: better melos commands (#1054)

README.md
=> add section

README.md
=> better toc

README.md
=> add platforms

.github/workflows/cicd.yml, .github/workflows/dependency_check.yml, .github/workflows/pull_latest_lexicons.yml, .github/workflows/pull_latest_mod_resources.yml
=> optimize workflow

bin/generate_lexicon_matrix.dart, website/docs/lexicons/com/atproto/repo/uploadBlob.md, website/docs/lexicons/com/atproto/sync/getBlob.md, website/docs/lexicons/com/atproto/sync/getBlocks.md, website/docs/lexicons/com/atproto/sync/getCheckout.md, website/docs/lexicons/com/atproto/sync/getRecord.md, website/docs/lexicons/com/atproto/sync/getRepo.md, website/docs/lexicons/com/atproto/temp/importRepo.md, website/docs/lexicons/com/atproto/temp/pushBlob.md
=> feat: show encoding-only input/output (#1089)

bin/generate_lexicon_matrix.dart, website/docs/lexicons/com/atproto/repo/uploadBlob.md, website/docs/lexicons/com/atproto/sync/getBlob.md, website/docs/lexicons/com/atproto/temp/pushBlob.md
=> feat: escape `*` (#1107)

bin/generate_lexicon_matrix.dart, website/docs/lexicons/app/bsky/actor/profile.md, website/docs/lexicons/app/bsky/feed/generator.md, website/docs/lexicons/app/bsky/feed/like.md, website/docs/lexicons/app/bsky/feed/post.md, website/docs/lexicons/app/bsky/feed/repost.md, website/docs/lexicons/app/bsky/feed/threadgate.md, website/docs/lexicons/app/bsky/graph/block.md, website/docs/lexicons/app/bsky/graph/defs.md, website/docs/lexicons/app/bsky/graph/follow.md, website/docs/lexicons/app/bsky/graph/list.md, website/docs/lexicons/app/bsky/graph/listblock.md, website/docs/lexicons/app/bsky/graph/listitem.md, website/docs/lexicons/com/atproto/admin/defs.md, website/docs/lexicons/com/atproto/moderation/defs.md
=> #1109 #1110

.vscode/settings.json, bin/generate_lexicon_ids.dart, packages/atproto/CHANGELOG.md, packages/atproto/lib/src/nsids.g.dart, packages/atproto/lib/src/services/base_service.dart, packages/atproto/lib/src/services/identities_service.dart, packages/atproto/lib/src/services/labels_service.dart, packages/atproto/lib/src/services/moderation_service.dart, packages/atproto/lib/src/services/repositories_service.dart, packages/atproto/lib/src/services/servers_service.dart, packages/atproto/lib/src/services/sync_service.dart, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/base_xrpc_service.dart, packages/atproto_core/lib/src/sessions/sessions.dart, packages/atproto_core/test/src/base_xrpc_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/nsids.g.dart, packages/bluesky/lib/src/services/actors_service.dart, packages/bluesky/lib/src/services/base_service.dart, packages/bluesky/lib/src/services/feeds_service.dart, packages/bluesky/lib/src/services/graphs_service.dart, packages/bluesky/lib/src/services/notifications_service.dart, packages/bluesky/lib/src/services/unspecced_service.dart
=> refactor: Use optimized NSID (#1114)

packages/at_identifier/README.md, packages/at_uri/README.md, packages/atproto/README.md, packages/bluesky/README.md, packages/bluesky_cli/README.md, packages/bluesky_text/README.md, packages/did_plc/README.md, packages/lexicon/README.md, packages/multiformats/README.md, packages/nsid/README.md, packages/xrpc/README.md
=> docs: refactor

bin/generate_lexicon_matrix.dart, website/docs/lexicons/app/bsky/graph/defs.md, website/docs/lexicons/com/atproto/admin/defs.md, website/docs/lexicons/com/atproto/moderation/defs.md, website/docusaurus.config.js, website/pubspec.yaml, website/src/data/features.tsx, website/static/snippets/atproto_and_bluesky.dart, website/static/snippets/bluesky_text.dart, website/static/snippets/post_to_bluesky.dart, website/static/snippets/retry.dart
=> docs: better refs and add algolia search

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/services/entities/converter/thread_rule_converter.dart, packages/bluesky/pubspec.yaml
=> fix: converting Threadgate (#1128)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/services/repo_service.dart, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/services/feed_service.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/services/feed_service_test.dart, packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/pubspec.yaml, packages/did_plc/CHANGELOG.md, packages/did_plc/pubspec.yaml, packages/xrpc/CHANGELOG.md, packages/xrpc/lib/src/utils.dart, packages/xrpc/pubspec.yaml
=> feat: `nobody` option

bin/generate_support_api_matrix.dart, bin/generate_supported_api_matrix.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/services/notification_service.dart, website/docs/api_support_matrix.md, website/docs/packages/atproto.md, website/docs/packages/bluesky.md, website/docs/supported_api.md, website/docusaurus.config.js
=> feat: Generate API Support Matrix (#1133)

website/pubspec.yaml, website/static/snippets/atproto_and_bluesky.dart, website/static/snippets/bluesky_text.dart, website/static/snippets/firehose.dart, website/static/snippets/post_to_bluesky.dart, website/static/snippets/retry.dart
=> latest syntax

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/pubspec.yaml
=> feat: expose `RepoServiceExtension` (#1137)

bin/collect_auth_data.dart, bin/generate_supported_api_matrix.dart, data/auth.json, pubspec.yaml, website/docs/supported_api.md
=> feat: Collect auth data for docs (#1140)

packages/bluesky_cli/CHANGELOG.md, packages/bluesky_cli/lib/src/command/feed/post.dart, packages/bluesky_cli/lib/src/runner/bsky_runner.dart, packages/bluesky_cli/lib/src/version.g.dart, packages/bluesky_cli/pubspec.yaml
=> feat: add `--reply` option (#1144)

bin/generate_supported_api_matrix.dart, website/docs/supported_api.md
=> feat: add `paging` section (#1147)

bin/generate_lexicon_matrix.dart, website/docs/lexicons/app/bsky/actor/defs.md
=> docs: support lex array (#1154)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/moderation/utils/options.dart, packages/bluesky/lib/src/services/constants/content_label_visibility.dart, packages/bluesky/lib/src/services/entities/content_label_preference.g.dart, packages/bluesky/lib/src/services/entities/converter/content_label_preference_converter.dart, packages/bluesky/lib/src/services/entities/converter/preference_converter.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/moderation/suite/converter/moderation_options_behavior_scenario_label_converter.dart, packages/bluesky/test/src/moderation/suite/moderation_options_behavior_scenario.dart, packages/bluesky/test/src/moderation/suite/moderation_options_behavior_scenario.freezed.dart, packages/bluesky/test/src/moderation/suite/moderation_options_behavior_scenario.g.dart, packages/bluesky/test/src/moderation/suite/moderation_options_behavior_scenario_label.g.dart, packages/bluesky/test/src/services/constants/content_label_visibility_test.dart, packages/bluesky/test/src/services/suite/data/app/bsky/actor/getPreferences.json
=> refactor: Convert `show` values to `ignore` internally

bin/collect_auth_data.dart, bin/generate_supported_api_matrix.dart
=> fix: The method '[]' was called on null.

.github/workflows/pull_latest_lexicons.yml
=> remove build step

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/services/entities/tagged_suggestion.dart, packages/bluesky/lib/src/services/entities/tagged_suggestion.freezed.dart, packages/bluesky/lib/src/services/entities/tagged_suggestion.g.dart, packages/bluesky/lib/src/services/entities/tagged_suggestions.dart, packages/bluesky/lib/src/services/entities/tagged_suggestions.freezed.dart, packages/bluesky/lib/src/services/entities/tagged_suggestions.g.dart, packages/bluesky/lib/src/services/unspecced_service.dart, packages/bluesky/test/src/services/suite/data/app/bsky/unspecced/getTaggedSuggestions.json, packages/bluesky/test/src/services/unspecced_service_test.dart
=> feat: support `getTaggedSuggestions` (#1225)

packages/atproto/CHANGELOG.md, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/bluesky_cli/pubspec.yaml, packages/bluesky_text/CHANGELOG.md, packages/bluesky_text/pubspec.yaml, packages/did_plc/CHANGELOG.md, packages/did_plc/pubspec.yaml, packages/xrpc/CHANGELOG.md, packages/xrpc/lib/src/xrpc/exception/xrpc_exception.dart, packages/xrpc/pubspec.yaml, packages/xrpc/test/src/xrpc/exception/xrpc_exception_test.dart
=> refactor: better error messages (#1253)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/atproto.dart, packages/atproto/test/src/atproto_test.dart, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/clients/service_context.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/bluesky.dart, packages/bluesky/test/src/bluesky_test.dart
=> feat: exposed `.service` and `.relayService` properties (#1254)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/services/entities/saved_feeds_preference.dart, packages/bluesky/lib/src/services/entities/saved_feeds_preference.freezed.dart, packages/bluesky/lib/src/services/entities/saved_feeds_preference.g.dart, packages/bluesky/test/src/services/suite/data/app/bsky/actor/getPreferences.json
=> feat: add `.timelineIndex` on `SavedFeedsPreference` (#1251)

packages/atproto/lib/src/atproto.dart, packages/atproto/lib/src/services/repo_service.dart, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/clients/service_context.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/bluesky.dart, packages/bluesky_cli/lib/src/command/bsky_command.dart, packages/xrpc/CHANGELOG.md, packages/xrpc/lib/src/http/http.dart, packages/xrpc/lib/src/xrpc/xrpc.dart, packages/xrpc/lib/xrpc.dart, packages/xrpc/test/src/xrpc/xrpc_test.dart
=> feat: support `parameters` on `post` method (#1252)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/services/entities/adaptor/subscribe_repo_updates_adaptor.dart, packages/atproto_core/CHANGELOG.md, packages/bluesky/CHANGELOG.md
=> fix: made sure to check if the subscribeRepos blocks can be decoded

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/services/server_service.dart
=> feat: add `plcOp` param (#969)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/services/entities/server_info.dart, packages/atproto/lib/src/services/entities/server_info.freezed.dart, packages/atproto/lib/src/services/entities/server_info.g.dart, packages/atproto/lib/src/services/temp_service.dart, packages/atproto/pubspec.yaml, packages/atproto/test/src/services/suite/data/com/atproto/server/describeServer.json, packages/atproto/test/src/services/temp_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml
=> feat: added `did` property (#1279)

packages/atproto/CHANGELOG.md, packages/atproto/lib/atproto.dart, packages/atproto/lib/src/services/entities/service_auth_token.dart, packages/atproto/lib/src/services/entities/service_auth_token.freezed.dart, packages/atproto/lib/src/services/entities/service_auth_token.g.dart, packages/atproto/lib/src/services/server_service.dart, packages/atproto/test/src/services/server_service_test.dart, packages/atproto/test/src/services/suite/data/com/atproto/server/getServiceAuth.json, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart
=> feat: `getServiceAuth` (#1280)

packages/at_uri/CHANGELOG.md, packages/at_uri/lib/src/at_uri.dart, packages/at_uri/pubspec.yaml, packages/atproto/CHANGELOG.md, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/bluesky_cli/lib/src/version.g.dart, packages/bluesky_cli/pubspec.yaml, packages/did_plc/CHANGELOG.md, packages/did_plc/pubspec.yaml
=> feat: (#1300)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/services/entities/feed_view_preference.dart, packages/bluesky/lib/src/services/entities/feed_view_preference.freezed.dart, packages/bluesky/lib/src/services/entities/feed_view_preference.g.dart, packages/bluesky/test/src/services/suite/data/app/bsky/actor/getPreferences.json
=> feat:  support `lab_mergeFeedEnabled ` (#1335)

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/atproto.dart, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/clients/service_context.dart, packages/atproto_core/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/bluesky.dart, packages/bluesky/lib/src/services/service_context.dart, packages/bluesky/pubspec.yaml, packages/did_plc/CHANGELOG.md, packages/did_plc/pubspec.yaml
=> feat: global headers (#1360)

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/bluesky.dart, packages/bluesky/lib/src/services/entities/converter/preference_converter.dart, packages/bluesky/lib/src/services/entities/preference.dart, packages/bluesky/lib/src/services/entities/preference.freezed.dart, packages/bluesky/lib/src/services/entities/saved_feed.dart, packages/bluesky/lib/src/services/entities/saved_feed.freezed.dart, packages/bluesky/lib/src/services/entities/saved_feed.g.dart, packages/bluesky/lib/src/services/entities/saved_feeds_pref_v2.dart, packages/bluesky/lib/src/services/entities/saved_feeds_pref_v2.freezed.dart, packages/bluesky/lib/src/services/entities/saved_feeds_pref_v2.g.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/services/suite/data/app/bsky/actor/getPreferences.json
=> `saved_feeds_pref_v2` (#1420)

bin/utils.dart
=> add chat/bsky and tools/ozone

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/moderation.dart, packages/bluesky/lib/src/moderation/decision.dart, packages/bluesky/lib/src/moderation/types/behaviors/moderation_cause_label.dart, packages/bluesky/lib/src/moderation/types/behaviors/moderation_cause_label.freezed.dart, packages/bluesky/lib/src/moderation/types/behaviors/moderation_opts.dart, packages/bluesky/lib/src/moderation/types/const/labels.dart, packages/bluesky/lib/src/moderation/types/interpreted_label_value_definition.dart, packages/bluesky/lib/src/moderation/types/interpreted_label_value_definition.freezed.dart, packages/bluesky/lib/src/moderation/types/labels.dart, packages/bluesky/lib/src/moderation/utils.dart, packages/bluesky/lib/src/services/entities/labeler_policies.dart, packages/bluesky/lib/src/services/entities/labeler_policies.freezed.dart, packages/bluesky/lib/src/services/entities/labeler_policies.g.dart, packages/bluesky/lib/src/services/entities/labeler_view_detailed.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/moderation/suite/moderation_custom_labels_test.dart, packages/bluesky/test/src/moderation/suite/moderation_quote_posts_test.dart, packages/bluesky/test/src/services/labeler_service_test.dart, packages/bluesky_chat/CHANGELOG.md, packages/bluesky_chat/lib/src/ids.g.dart, packages/bluesky_chat/lib/src/nsids.g.dart, packages/bluesky_chat/pubspec.yaml
=> getLabelDefinitions

packages/atproto/CHANGELOG.md, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/sessions/auth_scope.dart, packages/atproto_core/lib/src/sessions/auth_token.g.dart, packages/atproto_core/pubspec.yaml, packages/atproto_core/test/src/sessions/auth_scope_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/bluesky_chat/CHANGELOG.md, packages/bluesky_chat/lib/src/ids.g.dart, packages/bluesky_chat/lib/src/nsids.g.dart, packages/bluesky_chat/pubspec.yaml, packages/did_plc/CHANGELOG.md, packages/did_plc/pubspec.yaml
=> fix: Add appPassPrivileged scope

packages/bluesky/lib/src/moderation/types/mute_words.dart
=> fix: Update mute_words.dart

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/moderation/utils.dart, packages/bluesky/pubspec.yaml, packages/bluesky_chat/CHANGELOG.md, packages/bluesky_chat/pubspec.yaml
=> fix: getLabelDefinitions

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/moderation/utils.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/moderation/utils_test.dart, packages/bluesky_chat/CHANGELOG.md, packages/bluesky_chat/pubspec.yaml
=> fix: getLabelerHeaders

packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/moderation/utils.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/services/suite/data/app/bsky/labeler/getServices.json, packages/bluesky_chat/CHANGELOG.md, packages/bluesky_chat/pubspec.yaml
=> fix: getModerationPrefs

packages/atproto/CHANGELOG.md, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/build.yaml, packages/atproto_core/lib/src/sessions/auth_token.g.dart, packages/atproto_core/lib/src/sessions/session.g.dart, packages/atproto_core/lib/src/utils/blob.g.dart, packages/atproto_core/lib/src/utils/blob_ref.g.dart, packages/atproto_core/pubspec.yaml, packages/atproto_test/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml, packages/bluesky_chat/CHANGELOG.md, packages/bluesky_chat/pubspec.yaml, packages/did_plc/CHANGELOG.md, packages/did_plc/pubspec.yaml, packages/lexicon/CHANGELOG.md, packages/lexicon/lib/src/types/core/lexicon_doc.g.dart, packages/lexicon/pubspec.yaml
=> fix: explicit_to_json: true

packages/atproto/CHANGELOG.md, packages/atproto/example/example.dart, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/clients/service_context.dart, packages/atproto_core/pubspec.yaml, packages/atproto_core/test/src/clients/service_context_test.dart, packages/atproto_test/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/example/example.dart, packages/bluesky/pubspec.yaml, packages/bluesky_chat/CHANGELOG.md, packages/bluesky_chat/lib/src/bluesky_chat.dart, packages/bluesky_chat/pubspec.yaml, packages/bluesky_chat/test/src/bluesky_chat_test.dart, packages/did_plc/CHANGELOG.md, packages/did_plc/pubspec.yaml, website/docs/packages/atproto.md, website/docs/packages/bluesky.md
=> feat: resolve pds host dynamically (#1543)

packages/lexicon/CHANGELOG.md, packages/lexicon/lib/lexicon.dart, packages/lexicon/pubspec.yaml
=> expose LexXrpcSubscriptionMessage

packages/atproto/CHANGELOG.md, packages/bluesky/CHANGELOG.md
=> add changelogs

bin/validate_dependencies.dart, packages/atproto/CHANGELOG.md, packages/atproto/lib/core.dart, packages/atproto/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/README.md, packages/bluesky/pubspec.yaml
=> expose session extension

bin/validate_dependencies.dart, packages/atproto/CHANGELOG.md, packages/atproto/pubspec.yaml, packages/atproto_core/CHANGELOG.md, packages/atproto_core/lib/src/clients/service_context.dart, packages/atproto_core/lib/src/types/session.dart, packages/atproto_core/pubspec.yaml, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml
=> expose `.atprotoPdsEndpoint`

packages/atproto/lib/src/services/repo_service.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/pubspec.yaml
=> fix: deleteRecord

bin/collect_auth_data.dart, bin/generate_lex_annotations.dart, bin/generate_lexicon_docs.dart, bin/generate_lexicon_matrix.dart, bin/generate_supported_api_matrix.dart, bin/pull_latest_lexicons.dart, bin/update_examples_document.dart, bin/utils.dart, bin/validate_dependencies.dart, pubspec.yaml, website/docs/supported_api.md
=> refactor: supported api

website/package.json
- https://docusaurus.io/blog/releases/3.0
=> bump docusaurus v3

website/package.json
- https://docusaurus.io/blog/releases/3.6
=> bump docusaurus v3.6

packages/bluesky/lib/src/services/constants/feed_filter.dart, packages/bluesky/test/src/services/constants/feed_filter_test.dart
Add latest feed filter available on bluesky
=> add postsWithVideo

packages/atproto/CHANGELOG.md, packages/atproto/lib/src/services/codegen/com/atproto/moderation/defs/reason_type.dart, packages/atproto/pubspec.yaml, packages/atproto/test/src/services/suite/com/atproto/moderation_service_test.dart, packages/bluesky/CHANGELOG.md, packages/bluesky/lib/src/services/codegen/app/bsky/actor/defs/status_view_status.dart, packages/bluesky/lib/src/services/codegen/app/bsky/actor/status/main_status.dart, packages/bluesky/lib/src/services/codegen/app/bsky/feed/defs/generator_view_content_mode.dart, packages/bluesky/lib/src/services/codegen/app/bsky/feed/defs/interaction_event.dart, packages/bluesky/lib/src/services/codegen/app/bsky/feed/generator/main_content_mode.dart, packages/bluesky/lib/src/services/codegen/app/bsky/graph/defs/list_purpose.dart, packages/bluesky/lib/src/services/codegen/tools/ozone/moderation/defs/subject_review_state.dart, packages/bluesky/lib/src/services/codegen/tools/ozone/moderation/getAccountTimeline/timeline_item_summary_event_type.dart, packages/bluesky/lib/src/services/codegen/tools/ozone/report/defs/reason_type.dart, packages/bluesky/lib/src/services/codegen/tools/ozone/server/getConfig/viewer_config_role.dart, packages/bluesky/lib/src/services/codegen/tools/ozone/setting/defs/option_manager_role.dart, packages/bluesky/lib/src/services/codegen/tools/ozone/setting/upsertOption/main_manager_role.dart, packages/bluesky/lib/src/services/codegen/tools/ozone/team/addMember/main_role.dart, packages/bluesky/lib/src/services/codegen/tools/ozone/team/defs/member_role.dart, packages/bluesky/lib/src/services/codegen/tools/ozone/team/updateMember/main_role.dart, packages/bluesky/pubspec.yaml, packages/bluesky/test/src/moderation/suite/utils/mock.dart, packages/bluesky/test/src/services/suite/app/bsky/graph_service_test.dart, packages/lex_gen/lib/src/services/object/lex_known_values.dart, packages/lex_gen/lib/src/services/rule.dart, pubspec.yaml
- Enhanced getLexKnownValuesElementName to handle lexicon ID context
- Fixed naming conflicts in generated enum values by prefixing with lexicon namespace
- Updated generated code for status view status and other enum types
- Reverted melos dependency to v6.0.0 for compatibility
Changes affect:
- Lexicon code generation logic for known values
- Generated enum naming to prevent conflicts
- Multiple codegen files with improved naming consistency
=> fix: improve lexicon known values naming and resolve conflicts

CODE_OF_CONDUCT.md, CONTRIBUTING.md
- Simplify CODE_OF_CONDUCT structure and remove unnecessary TOC
- Update to Contributor Covenant v2.1 (from v1.4)
- Streamline CONTRIBUTING.md with clearer sections
- Add development setup instructions with specific commands
- Include code style guidelines for Dart projects
- Add Getting Started section for new contributors
- Improve readability and reduce redundancy
=> docs: Optimize CODE_OF_CONDUCT and CONTRIBUTING guidelines
